# Generated by Django 4.2.5 on 2023-09-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_myuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
