# Generated by Django 4.2.5 on 2023-09-20 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_myuser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=30)),
                ('report', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PreliminaryDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.diagnosis')),
                ('farmer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('prescription', models.TextField()),
                ('expert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.myuser')),
                ('prelim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.preliminarydiagnosis')),
            ],
        ),
    ]
