# Generated by Django 4.2.5 on 2023-09-20 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_diagnosis_preliminarydiagnosis_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preliminarydiagnosis',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.myuser'),
        ),
    ]
