# Generated by Django 4.2.5 on 2023-09-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_preliminarydiagnosis_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='preliminarydiagnosis',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
    ]
