# Generated by Django 4.2.5 on 2023-09-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_preliminarydiagnosis_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='prescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
