# Generated by Django 4.2.5 on 2023-09-20 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_appointment_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.myuser'),
        ),
    ]
