# Generated by Django 4.2.5 on 2023-09-21 11:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_appointment_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='preliminarydiagnosis',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
