# Generated by Django 4.2.5 on 2023-09-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='preliminarydiagnosis',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
    ]
