# Generated by Django 4.2.5 on 2023-09-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_preliminarydiagnosis_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='type_choices',
            field=models.IntegerField(choices=[(1, 'Audio'), (2, 'Video'), (3, 'Chat')], default=1),
        ),
    ]
