# Generated by Django 4.2.5 on 2023-09-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_appointment_type_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosis',
            old_name='disease',
            new_name='disease_name',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='disease_tag',
            field=models.CharField(default='old_table_remnants', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='plant',
            field=models.CharField(default='old_table_remnants', max_length=30),
            preserve_default=False,
        ),
    ]
