# Generated by Django 4.2.5 on 2023-09-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_appointment_expert'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='description_from_farmer',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
